apiVersion: v1
entries:
  mongodb:
  - apiVersion: v2
    appVersion: 0.13.0
    created: "2025-04-25T07:34:20.65523505Z"
    description: A Helm chart to deploy Mongodb replicatsets with official community
    digest: d19ee8e4fe5030dbeae364b3be2a896bb2d2a343a5261cac2ebef7d81bef8e1d
    icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
    keywords:
    - mongodb
    - database
    - nosql
    name: mongodb
    type: application
    urls:
    - https://plopoyop.github.io/charts/mongodb/mongodb-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.12.0
    created: "2025-04-03T19:30:52.734212032Z"
    description: A Helm chart to deploy Mongodb replicatsets with official community
    digest: a5586b66a3d0c40c602aadca63be1a9775ff5206497611f3318dc0362304bf45
    icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
    keywords:
    - mongodb
    - database
    - nosql
    name: mongodb
    type: application
    urls:
    - https://plopoyop.github.io/charts/mongodb/mongodb-0.1.0.tgz
    version: 0.1.0
  mongodb-instance:
  - apiVersion: v2
    appVersion: 8.0.18
    created: "2026-02-08T20:25:25.957115Z"
    description: Deploy and manage a MongoDB ReplicaSet on Kubernetes using the MongoDB
      Kubernetes Operator.
    digest: 6c978d9ddb751d11007fdb3503a73f77a3b69f0140ec99ff5f510b56a6ccc18a
    icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
    keywords:
    - mongodb
    - database
    - nosql
    - kubernetes
    - operator
    name: mongodb-instance
    type: application
    urls:
    - https://plopoyop.github.io/charts/mongodb-instance/mongodb-instance-0.1.1.tgz
    version: 0.1.1
generated: "2026-02-08T20:25:25.955181672Z"
